name: Appstore Deployment PR 

on:
  pull_request:
    branches:
      - main

jobs:
  deploy_ios:
    name: Deploy build to TestFlight
    runs-on: macOS-latest
    steps:
      - name: Checkout code from ref
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Get the PR description
        run: |
          # Get the PR description using GitHub API
          PR_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                           -H "Accept: application/vnd.github.v3+json" \
                           "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" \
                         | jq -r '.body')


          # Extract "What to Test" bullet points using regular expressions
          WHAT_TO_TEST=$(echo "$PR_DESCRIPTION" | grep -A999999 '### What to Test' | sed -n '/### What to Test/,$p' | sed '/###/d' | sed '/^[[:space:]]*-[[:space:]]*\[[ x]\]/!d; s/^[[:space:]]*-[[:space:]]*\[[ x]\]//')

          # Set the extracted content in an environment variable with "\n" separator
          # echo "WHAT_TO_TEST=${WHAT_TO_TEST}" >> $GITHUB_ENV

          echo "WHAT_TO_TEST<<EOF" >> $GITHUB_ENV
          echo "$WHAT_TO_TEST" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Display WHAT_TO_TEST Content
        run: |
          echo "Extracted 'What to Test': ${{ env.WHAT_TO_TEST }}"

      # - uses: webfactory/ssh-agent@v0.7.0
      #   with:
      #     ssh-private-key: ${{ secrets.MATCH_REPO_KEY }}

      # - name: Run Flutter tasks
      #   uses: subosito/flutter-action@v2
      #   with:
      #     flutter-version: '3.13.4'
      # - run: flutter clean
      # - run: flutter pub get

      # # Assign a unique build identifier using PR number.
      # - name: Assign Build Identifier
      #   run: echo "BUILD_IDENTIFIER=PR${{ github.event.pull_request.id }}" >> $GITHUB_ENV

      # - run: flutter build ios --release --no-codesign --no-tree-shake-icons --build-name=$BUILD_IDENTIFIER --build-number=$BUILD_IDENTIFIER

      # - name: Install Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '2.7'
      #     bundler-cache: true
      #     working-directory: 'ios'

      # - name: Deploy iOS Beta to TestFlight via Fastlane
      #   uses: maierj/fastlane-action@v3.0.0
      #   with:
      #     lane: beta
      #     subdirectory: ios
      #   env:
      #     TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
      #     TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
      #     APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      #     APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      #     APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
      #     GIT_AUTHORIZATION: ${{ secrets.GIT_AUTHORIZATION }}
      #     APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
      #     APPLE_ID: ${{ secrets.APPLE_ID }}
      #     APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
      #     DEV_PORTAL_TEAM_ID: ${{ secrets.DEV_PORTAL_TEAM_ID }}
      #     GIT_CERTS_URL: ${{ secrets.GIT_CERTS_URL }}
      #     MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      #     MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
      #     BUILD_IDENTIFIER: ${{ env.BUILD_IDENTIFIER }} # Pass the build identifier to Fastlane
      #     PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
      #     PULL_REQUEST_BRANCH_NAME: ${{ github.head_ref }}
